version: "3.7"

services:
  # Webserver
  webserver:
    build:
      context: ./bin/webserver
    image: sashwat-project-devops/openlitespeed
    container_name: "openlitespeed"
    restart: "always"
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    working_dir: /var/www/vhosts/localhost/html/
    links:
      - mariadb
    volumes:
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${OPENLITESPEED_CONFIG-./config/openlitespeed-config/httpd_config.conf}:/usr/local/lsws/conf/httpd_config.conf
      - ${OPENLITESPEED_VHOST-./config/openlitespeed-vhosts/vhconf.conf}:/usr/local/lsws/conf/vhosts/Example/vhconf.conf
      - ${DOCKER_CONFIG-./config/openlitespeed-docker/docker.conf}:/usr/local/lsws/conf/templates/docker.conf
      - ${LOG_DIR-./logs/openlitespeed}:/usr/local/lsws/logs/
  # API Server
  apiserver:
    build:
      context: ./bin/apiserver
    container_name: "apiserver"
    restart: "always"
    ports:
      - "${APISERVER_PORT}:5000"
    links:
      - webserver
      - mariadb
  # MySQL Server
  mariadb:
    build:
      context: ./bin/mariadb
    image: sashwat-project-devops/mariadb
    container_name: "mariadb"
    restart: "always"
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      TZ: ${TimeZone}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  # PHPMyAdmin server
  phpmyadmin:
    build:
      context: ./bin/phpmyadmin
    image: sashwat-project-devops/phpmyadmin
    container_name: "phpmyadmin"
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: ${HOST_MACHINE_MYSQL_PORT}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    volumes:
      - /sessions
